apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-app
  labels:
    app: log-output-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-app
  template:
    metadata:
      labels:
        app: log-output-app
    spec:
      containers:
        - name: log-output
          image: log-output:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  labels:
    app: log-output-app
spec:
  selector:
    app: log-output-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 